export enum CategoriasType {
  PLOMERO = "PLOMERO",
  CARPINTERO = "CARPINTERO",
  ELECTRICISTA = "ELECTRICISTA",
  GASISTA = "GASISTA",
  PINTOR = "PINTOR",
  CERRAJERO = "CERRAJERO",
  MECANICO = "MECANICO",
  TECNICO = "TECNICO",
}