export enum CategoriasType {
  PLOMERO = 'PLOMERO',
  AIRE_ACONDICIONADO = 'A-A',
  ALBAÑIL = 'ALBAÑIL',
  ARQUITECTO = 'ARQUITECTO',
  BARBERO = 'BARBERO',
  CERRAJERO = 'CERRAJERO',
  CARPINTERO = 'CARPINTERO',
  JARDINERO = 'JARDINERO',
  SEGURIDAD = 'SEGURIDAD',
  ELECTRICISTA = 'ELECTRICISTA',
  MASCOTAS = 'MASCOTAS',
  VEHICULOS = 'VEHICULOS',
  PINTOR = 'PINTOR',
  TECNICO = 'TECNICO'
}